### ISSUE TITLE
Redis for session in LegacyBridge

### ISSUE THREAD

**Issue by ReaperSoon** [ezsystems/LegacyBridge#142]
Hi,

We use Redis as stash default driver  with snc_redis vendor. And also another redis instance in another port for session.
Here is my configuration :

```yaml
stash:
    caches:
        default:
            drivers: [ Redis ]
            Redis:
                servers:
                    -
                        server: 'myredis'
                        port: 6380
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://myredis
            logging: %kernel.debug%
        cache:
            type: predis
            alias: cache
            dsn: redis://myredis:6380
            logging: true
        session:
            type: predis
            alias: session
            dsn: redis://myredis:6379`
```

But my backoffice sessions still use file sessions in `/var/lib/php/sessions/`. If i change my php.ini like this :
```ini
[Session]
; Handler used to store/retrieve data.
; http://php.net/session.save-handler
session.save_handler = redis
session.save_path = "tcp://localhost:6379"
```
it works, but I don't want to change the whole configuration of my server.

Why the backoffice does not use the symfony configuration for the session handler ?
Do I need to configure ezpublish_legacy to use Redis handler ?

Thanks,
Steve
