### ISSUE TITLE
ezpublish_legacy handle Not foud error (404)

### ISSUE THREAD

**Issue by kemoc** [ezsystems/LegacyBridge#87]
in my configuration
ezplatform.yml
```
ez_publish_legacy:
    #enabled: false
    system:
        ztest:
            legacy_mode: false
```
routing.yml
```
#...
_ezplatformRepositoryFormsRoutes:
    resource: "@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml"

_contentOnTheFly:
    resource: "@ContentOnTheFlyBundle/Resources/config/routing.yml"
    prefix:   '%ezpublish_rest.path_prefix%'

_ezpublishLegacyRoutes:
    resource: "@EzPublishLegacyBundle/Resources/config/routing.yml"

#<end of file>
```
My eZPlatform is v1.8.1 but this problem is also on v1.3.x
